### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by majijn** [LuoXiao-Wing/Tea-TheStoryOfALeaf#12]
I've been having an issue where im pplaying singleplayer, and yet my serverside of singlelplayer stops working, I dont crash, but as soon as I try to leave the world, it crashes (also I cant interact with inventories, and breaking blocks drops nothing) , when I load back the world, it looks fine, and works fine for 40 minutes to 2 hours, I'm trying to troubleshoot what's causing this and I just found this on the logs

`Exception caught during firing event net.minecraftforge.fml.client.event.ConfigChangedEvent$OnConfigChangedEvent@1c0f5364:
java.lang.NullPointerException
	at roito.teastory.common.EventLoader.onConfigurationChangedEvent(EventLoader.java:154)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_801_EventLoader_onConfigurationChangedEvent_OnConfigChangedEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.client.config.GuiConfig.func_146284_a(GuiConfig.java:322)
	at mezz.jei.config.JEIModConfigGui.func_146284_a(JEIModConfigGui.java:80)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraftforge.fml.client.config.GuiConfig.func_73864_a(GuiConfig.java:369)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraftforge.fml.client.config.GuiConfig.func_146274_d(GuiConfig.java:359)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

[latest.log](https://github.com/LuoXiao-Wing/Tea-TheStory/files/2060418/latest.log) heres the entire log if that helps

would this be what's doing it? because so far I thought it was mobs doing it (because this error doesnt happen on peaceful)

edit: figured out what was causing my issues! it was historized medicine! but I really dont know why I was getting that error before the other thing happened.

**Comment by RoShioLeo** [comment]
Sorry, I didn't see it until just now.

**Comment by RoShioLeo** [comment]
It looks like lost files. It's strange. Not only does my mod have problems.

**Comment by RoShioLeo** [comment]
I'll solve NullPointerException. That's only what I can do.
Thank you.
By the way, I stayed at school for 9 days so I couldn't reply in time.

**Comment by majijn** [comment]
not a problem! that stuff takes priority!! I only found that error message in the first place because I was looking for a different issue that was caused by a different mod!
